name: github pages

on:
  push:
    branches: [master]
  pull_request:
    
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1

      - name: Doxygen Action
        run: |
          echo "Preparing files for documentation"
          sudo apt install doxygen
          cd concord
          echo $(ls)
          make docs
          echo "Generating HTML output"
          doxygen

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3.7.3
        if: github.ref == 'refs/heads/master'
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: gh-pages
          publish_dir: ./concord/docs/html
