name: github pages

on:
  push:
    branches: [master]
  pull_request:
    
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1

      - name: Dependencies
        run: |
          echo "Preparing Concord"
          git clone https://github.com/Cogmasters/concord
          make -C concord docs
          cp Doxyfile concord/Doxyfile
          echo "Install Jinja2"
          pip install -U jinja2
          echo "Install Sphinx"
          pip install sphinx
          pip install pydata_sphinx_theme
          echo "Install Breathe"
          pip install breathe

      - name: Doxygen Action
        uses: mattnotmitt/doxygen-action@v1.3.1
        with:
          working-directory: 'concord/'

      - name: Move XML to Concord-Docs
        run: sudo mv concord/docs/xml docs/

      - name: Breathe Action
        run: make -C docs html

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3.7.3
        if: github.ref == 'refs/heads/master'
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: gh-pages
          publish_dir: ./docs/build/html
