name: github pages

on:
  push:
    branches: [dev]
  pull_request:
    
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1

      - name: Install Doxygen-1.9.3
        run: |
          echo "Install wget"
          sudo apt install wget
          echo "Install graphviz"
          sudo apt install graphviz
          echo "Fetching binary distribution"
          wget https://www.doxygen.nl/files/doxygen-1.9.3.linux.bin.tar.gz
          echo "Extract files from tar file"
          tar -xvf doxygen-1.9.3.linux.bin.tar.gz

      - name: Doxygen Action
        run: |
          echo "Preparing files for documentation"
          sudo mv doxygen-1.9.3/bin/doxygen concord/
          make -C concord docs
          echo "Generating HTML output"
          cd concord
          ./doxygen

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3.7.3
        if: github.ref == 'refs/heads/dev'
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: gh-pages
          publish_dir: ./concord/docs/html
