name: github pages

on:
  push:
    branches: [master]
  pull_request:
    
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1

      - name: Test
        run: echo $(pwd)

      - name: Dependencies
        run: git clone https://github.com/cee-studio/orca

      - name: Doxygen Action
        uses: mattnotmitt/doxygen-action@v1.3.1

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3.7.3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: gh-pages
          publish_dir: ./docs/html
