name: github pages

on:
  push:
    branches: [master]
  pull_request:
    
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1

      - name: Dependencies
        run: |
          echo "Preparing Orca"
          git clone https://github.com/cee-studio/orca
          cd orca && ./scripts/get-cee-utils.sh && cd ..
          cp Doxyfile orca/Doxyfile
          echo "Install Sphinx"
          pip install sphinx
          pip install sphinx_rtd_theme
          echo "Install Breathe"
          pip install breathe

      - name: Doxygen Action
        uses: mattnotmitt/doxygen-action@v1.3.1
        with:
          working-directory: 'orca/'

      - name: Move XML to Orca-Docs
        run: sudo mv orca/docs/xml docs/

      - name: Breathe Action
        run: make -C docs html

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3.7.3
        # if: github.ref == 'refs/heads/master'
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: gh-pages
          publish_dir: ./docs/build/html
